package rules.com.ftn
// list any import classes here
import com.ftn.model.Message;

// declare any global viriables here

rule "Your first rule"
    when
        $m: Message(message == "hello there", myStatus: status)
    then
        System.out.println($m.getMessage());
        modify($m){setMessage("Godby there"), setStatus(Message.GOODBYE)};
end

rule "Your second rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //action
end
/*
package rules.com.ftn
import com.ftn.model.Message;
rule "Hello World"
    when
        $m: Message(status == Message.HELLO, myMessage: message)
    then
        System.out.println( myMessage);
    
        modify($m){setMessage("Goodbye cruel world"), setStatus( Message.GOODBYE) };
end

rule "GoodBye"
    //include attributes such as "salience" here...
    when
        Message(status == Message.GOODBYE, myMessage: message)
    then
        System.out.println(myMessage);
end
*/