package rules.com.ftn
import com.ftn.model.Message;



rule "Hello World"
    when
        $m: Message(status == Message.HELLO, myMessage: message)
    then
        System.out.println( myMessage);
    
        modify($m){setMessage("Goodbye cruel world"), setStatus( Message.GOODBYE) };
end

rule "GoodBye"
    //include attributes such as "salience" here...
    when
        Message(status == Message.GOODBYE, myMessage: message)
    then
        System.out.println(myMessage);
end