//created on: Mar 27, 2017
package rules.rules

import com.ftn.model.Customer;
import com.ftn.model.Order;

rule "Categorize Customer - Gold"
    when
	     $c: Customer( category == Customer.Category.NA )
	     $o: Order( customer == $c, orderLines.size() > 10 )
    then
        modify($c){ setCategory(Customer.Category.GOLD); }

end

rule "simple attribute example"
	enabled false
	when
		Customer( )
	then
		System.out.println("we have a customer");
end